express-labs/pure-react-carousel

package.json

The use case here is that if — like me — you keep code in a directory
like `~/dev/pure-react-carousel/`, tests were not being run.
See [Jest documentation](https://facebook.github.io/jest/docs/en/configuration.html#testpathignorepatterns-array-string) for details on `rootDir`.

Add `<rootDir>` to Jest ignore paths

---

src/Slider/slider.css

Hello,
I am playing around with the Carousel.
I've noticed that the default slide animation `.sliderAnimation` doesn't have the `will-change` CSS property which makes the animation a little bit more performant by reducing the browser repaints.
This is a simple Pull Request, I have not cloned nor ran any tests after this edit.

Simple .sliderAnimation performance improvement

---

src/CarouselProvider/CarouselProvider.jsx
src/CarouselProvider/__tests__/CarouselProvider.test.jsx

Ref: https://github.com/express-labs/pure-react-carousel/issues/76
Previously, `isNewCurrentSlide` was true whenever *any* props changed,
if there was no previous `currentSlide` prop.
With this change, we only consider it a "new" current slide if:
- There was a `currentSlide` prop provided
- The `currentSlide` prop value is different than the actual current slide
I believe the tests cover the important cases here, but open to feedback!

Fix isNewCurrentSlide logic to prevent updating accidentally (fixes #76)

---

README.md

I'm guessing this is wrong since there are no other mentions of `withProvider`.

Typo fix in code example

---

README.md
package-lock.json
package.json
src/App/App.jsx
src/App/examples/Example10/CustomSpinner.jsx
src/App/examples/Example10/CustomSpinner.scss
src/App/examples/Example10/Example10.jsx
src/App/examples/Example10/index.js
src/App/examples/index.js
src/ImageWithZoom/ImageWithZoom.jsx
src/ImageWithZoom/__tests__/ImageWithZoom.test.jsx
src/Slider/Slider.jsx
src/Slider/__tests__/Slider.test.jsx
typings/carouselElements.d.ts

Custom Spinner Options

---

src/Slide/Slide.jsx

Adds missing `role="option"` and changes `aria-hidden` to `aria-selected`.
Resources:
- https://stackoverflow.com/questions/39523226/what-is-role-listbox-used-when-creating-carousel
- https://stackoverflow.com/questions/16840054/wai-aria-roles-for-carousels-a-k-a-sliders-slideshows-galleries
- https://jongund.github.io/aria-examples/bootstrap-carousel/

Slide element accessibility improvement

---

src/Slider/Slider.jsx

When I test my website through [w3 validator](https://validator.w3.org/) I get an error on the Slider component's `<div>`, saying that _`step` is not allowed on element `div`_
This PR simply prevent `step` prop to be assigned to the HTML element.

Fix: Remove `step` attribute from Slider div

---

typings/index.d.ts

* fix comment error (`totalSlides` is required instead of `orientation`)
* fix export CarouselProviderState instead of CarouselProviderProps error ( CarouselProviderState is not needed for consumer typing while CarouselProviderProps is)

Fix typing error for CarouselProvider

---

README.md
src/DotGroup/DotGroup.jsx
src/DotGroup/__tests__/DotGroup.test.jsx

This PR allow <DotGroup /> to accept a prop `renderDots()` in order to override the default rendering
```
<DotGroup 
renderDots={(props) => {
// return JSX
})
/>
```

allow renderDots() in DotGroup to be overridden

---

src/Slider/Slider.jsx
src/Slider/__tests__/Slider.test.jsx

**What**:
Check that a touch is available before access properties on it to fire a `fakeOnDragMove`
**Why**:
We were seeing high rates of errors internally at Express in our bug tracking tools.
**How**:
Simple if check, and tests that validate it works 💯
**Checklist**:

fix(Slider): check if a touch exists before firing a fake drag

---

src/DotGroup/DotGroup.jsx
typings/carouselElements.d.ts

**What**:
* Add Typescript typings for the `renderDots` method
* Avoid passing the custom renderDots method back to itself
**Why**:
Could not use the `renderDots` method while using Typescript. 
I removed the parameter because it was unneeded
**Checklist**:
- [x ] Ready to be merged 
fixes #182

Allow using DotGroup prop renderDots in Typescript

---

src/App/examples/Example12/Example12.jsx
src/Slider/Slider.jsx
src/Slider/__tests__/Slider.test.jsx
src/Slider/index.js
src/helpers/component-config.js

**What**:
There was a recent addition to allow infinite scrolling with the buttons and with autoplay, but this isn't currently happening when a user swipes at the start or end of the carousel. This PR changes that.
**Why**:
When a user is swiping through pictures and hits the end of the carousel, it is cumbersome to have to swipe back through all of the photos instead of continuing to swipe forward.
**How**:
Modifying the computeCurrentSlide to account for when infinite is set to true.
**Checklist**:
Love what the team is doing with this! Thank you for the great package!

feature: infinite scroll works with swiping as well as buttons

---

src/Slider/Slider.jsx
src/Slider/__tests__/Slider.test.jsx

**What**:
Not pass `infinite` prop to `div`
**Why**:
It's not a valid prop
**How**:
By destructing it out
**Checklist**:
Introduced with #204

fix(Slider): do not pass infinite to div

---

typings/carouselElements.d.ts
typings/index.d.ts

Changed naming so that correct types are exported for ButtonNext
**What**:
Changed name from `buttonNextInterface` to `buttonNextProps`
**Why**:
It was incorrectly exporting interface instead of props
**How**:
Renamed exported type name
**Checklist**:

Fixed naming issue for ButtonNext types

---

README.md
src/index.js
typings/index.d.ts

**What**: Exports the carousel context and updates type definitions
**Why**: Allows for more flexibility when using the library, especially for devs that prefer hooks to HoC (there appears to be some demand for this already noted in #159, #175)
**How**: Exports the carousel context and updates type definitions
**Checklist**:
- ~[ ] Tests added and passing~ N/A, no behavioural change
Note that this provides only the basic necessities for integrating with hooks; more specific + re-usable hooks (e.g. `useCarouselState`, `useCurrentSlide`) could be implemented in the future with this change included

Export context

---

README.md
typings/index.d.ts

**What**: 
Udapte types definition into CarouselStoreInterface
Add missing library into README.md
**Why**:
Parameter 'src' implicitly had an 'any' type.
**How**:
Update next lines
`readonly subscribeMasterSpinner: (src: string) => void`
`readonly unsubscribeMasterSpinner: (src: string) => false | object`
`readonly masterSpinnerSuccess: (src: string) => void`
`readonly masterSpinnerError: (src: string) => void`
**Checklist**:
_- [ N/A ] Tests added and passing, no behavioural change_
Tracking from the last commit made by @saleb #235

Add missing types definition into CarouselStoreInterface

---

src/CarouselProvider/CarouselProvider.jsx
src/CarouselProvider/__tests__/CarouselProvider.test.jsx

**What**:
Prevent `currentSlide` from going out of bounds of `totalSlides`.
**Why**:
It's possible for a component to dynamically change the number of slides. If the number of slides is reduced such that `currentSlide` is past `totalSlides`, it results in a blank view.
**How**:
On `CarouselProvider`s update, `currentSlide` is being constrained to `totalSlides - 1` (i.e. the last slide).
**Checklist**:
- ~[ ] Documentation added/updated~ N/A, bugfix
- ~[ ] Typescript definitions updated~ N/A, no type changes

fix: prevent `currentSlide` from going out of bounds of `totalSlides`

---

README.md
src/App/App.jsx
src/App/examples/Example11/Example11.jsx
src/App/examples/Example5/Example5.jsx
src/App/examples/Example6/Example6.jsx
src/App/examples/Example7/Example7.jsx
src/App/examples/Example8/Example8.jsx

Guess who finally installed the spell checking plugin for VS Code?  This guy.
**What**:
Fixing spelling errors in documentation and comments.
**Why**:
Because: spelling.
**How**:
Used a spell checker.
**Checklist**:

Fixing various spelling errors.

---

src/CarouselProvider/CarouselProvider.jsx
src/CarouselProvider/__tests__/CarouselProvider.test.jsx

**What**:
This prevents the current slide from becoming -1 during re-renders under certain conditions. This is a fix for issue #247 
**Why**:
You shouldn't have a negative number slide.
**How**:
Updated CarouselProvider.jsx
**Checklist**:

Prevent negative slide number

---

src/ButtonBack/ButtonBack.jsx
src/ButtonBack/__tests__/ButtonBack.test.jsx
src/ButtonFirst/ButtonFirst.jsx
src/ButtonFirst/__tests__/ButtonFirst.test.jsx
src/ButtonLast/ButtonLast.jsx
src/ButtonLast/__tests__/ButtonLast.test.jsx
src/ButtonNext/ButtonNext.jsx
src/ButtonNext/__tests__/ButtonNext.test.jsx
src/Dot/Dot.jsx
src/Dot/__tests__/Dot.test.jsx

**What**:
Fixes #252 
Automatically pause "autoplay" (`isPlaying`) when the user changes slides using one of these HOC control components:
* `<ButtonNext />`
* `<ButtonBack />`
* `<ButtonFirst />`
* `<ButtonLast />`
* `<Dot />`
This mirrors the existing behavior where autoplay is paused when the user interacts with the Slider (i.e. drags on mobile).
**Why**:
Currently, the isPlaying interval timer doesn't reset when the user visits a slide using one of these buttons. The end result (as defined in #252) is that a user could progress to a slide and then immediately be progressed to another slide. I don't see why the user would EVER want this to happen.
**How**:
Set `isPlaying: false` in the CarouselProvider state in the onClick handler for each of the aforementioned HOCs.
**Checklist**:
I …

fix: autoplay interval bug

---

src/ImageWithZoom/ImageWithZoom.jsx
typings/carouselElements.d.ts

**What**:
The following props have been added to the `ImageWithZoom` component:
- `className`
- `imageClassName`
- `overlayClassName`
**Why**:
Before this change, it was impossible to add `className`s to the `ImageWithZoom` image and overlay components.  
Additionally, if a `className` was added to the container component via `filteredProps`, the container lost its existing styles.
**How**:
The new props were added in a manner which reflects the `Image` component's `className` prop.
**Checklist**:
- `ImageWithZoom` doesn't appear to have its own documentation separate to that of the `Image` component.

feat: Add className props to ImageWithZoom

---

src/App/App.jsx
src/App/examples/Example14/Example14.jsx
src/App/examples/Example14/index.js
src/App/examples/index.js
src/Slide/Slide.scss
src/Slider/Slider.scss

**What**:
Adds RTL support to fix https://github.com/express-labs/pure-react-carousel/issues/266
**Why**:
Allows the carousel content to be accessed when used on RTL pages, and updates the slide direction to match the direction of the text
**How**:
Adding `[dir="rtl"] &` selectors which flips the slider such that the slides are reversed and it visually translates in the opposite direction, and also flips each slide such that their content is not reversed.
**Checklist**:
The global attribute selector used to solve this issue feels a little hacky, but afaik there is no CSS-only solution which is more robust (the `:dir` pseudo-selector would be nice, but it doesn't have wide browser support)

fix: RTL support

---

typings/carouselElements.d.ts

**What**:
Added missing className typing for ButtonPlayProps interface 
**Why**:
ButtonPlay has ability to set custom className (and its already documented)
**How**:
Changes were implemented for TS typings
**Checklist**:

Add missing className for ButtonPlayProps typing

---

README.md
src/Dot/Dot.jsx
typings/carouselElements.d.ts

**What**:
Made children of Dot component optional
**Why**:
See issue #269 - when using Dot directly, there may no need to have any children
**How**:
Changed props and updated docs (hopefully :) )
**Checklist**:

Closes #269 : make dot children prop optional

---

typings/carouselElements.d.ts

This prop is supported by Slider but is not included in typings
**What**: Add trayProps to type definition. It is already a feature as outlined by the documentation
**Why**: Users who are using typescript do not have direct access to trayProps without adding custom typings
**How**: Add typing to carouselElements.d.ts
**Checklist**:

Update typings to include trayProps

---

src/Slide/Slide.jsx
src/Slide/__tests__/Slide.test.jsx

Slide set with unset position was causing the focus ring to expand past the parent
**What**: Slide set with unset position and when using isIntrinsicHeight was causing the focus ring to expand past the parent. See Issue #343 
**Why**:  When focused the slide position's CSS of relative was being overwritten to unset causing the focus ring to assume the width of the entire slider which is 200%.
**How**:  Removing the position unset keeps the focus ring set to the width of the slide.
**Checklist**:
- [ x ] Tests added and passing (N/A)
- [ x ] Ready to be merged

Fix issue #343

---

typings/index.d.ts

**What**:
Add Typings for isPlaying of CarouselState.
**Why**:
I want to control autoplay by isPlaying of CarouselState, and avoid type errors in this case.
```ts
carouselContext.setStoreState({ isPlaying: true });
```
**How**:
Add definition to typings/index.d.ts.
**Checklist**:

feat: Add Typings for isPlaying of CarouselState

---

README.md

**What**:
- `classname` heading typo change to `className`
**Why**:
- props are using camelcase, I suppose this was overlooked
**How**:
- just a text change
**Checklist**:

docs: readme heading typo

---

package.json

**What**:
Previously when running `npm install` you got an error saying that React is only supported up until version 17. You could get arround this by adding the following to project using this package:
```
"overrides": {
"react": "^18.1.0",
"react-dom": "^18.1.0"
},
```
But this PR is adding React 18.x as well so it's not needed anymore.
React 18 is really not that different from React 17. The project itself is still using React 16.
I tried this with the change, building it to a local package, installing it in another project and it worked just fine.
**Why**:
More projects is using React 18 every day and we don't want them to be forced to override dependencies if possible.
**How**:
Updated the peer dependencies for react and react-dom
**Checklist**:

Allow React 18 for peer deps

---

.all-contributorsrc

Semantic release action seems to no longer be working on PR. 
adding contributors to the contributor list and pushing this up to release
https://github.com/express-labs/pure-react-carousel/pull/415

feat: peer dependency react 18

---

README.md

**What**: Horizontal touch movements that are not 100% horizontal will scroll the page vertically, which could be frustrating to end users. 
**Why**: Feature request to implement a prevention of page scroll based on the delta positions of touch. 
**How**: A listener will be added to the window preventing the default behavior of the page, which is to scroll, if the delta positions of said touch movement is mostly horizontal in nature. The default threshold of these values is set to a horizontal delta greater than 15px and the vertical delta being less than 10px. These thresholds can be modified directly by the consumer of the library by changing the initial props and the feature can be opted out directly if so desired.
**Checklist**:

feat:preventVerticalScrollOnTouch

---

src/Slider/Slider.jsx
typings/index.d.ts

fix for https://github.com/express-labs/pure-react-carousel/issues/423

fix: typing-for-preventVerticalScroll

---

src/Slider/Slider.jsx
src/Slider/Slider.scss
src/Slider/__tests__/Slider.test.jsx

**What**:
I considered using an attribute instead of a class for the conditional logic, but ultimately thought that a class felt more appropriate in this case. I considered inverting the logic so that the `touchEnabled` conditional matched the `touchEnabled` prop, but it felt less good to always add the conditional class in the default case, rather than only adding it if overriding the `touchEnabled` prop. But happy to invert the logic if you prefer.
**Why**:
Fixes #442 
**How**:
Move the offending style into a style block which is excluded if a conditional class is appended.
**Checklist**:

Do not apply `touch-action` style if `touchEnabled === false`

---

src/ImageWithZoom/ImageWithZoom.jsx
src/ImageWithZoom/__tests__/ImageWithZoom.test.jsx
typings/carouselElements.d.ts

**What**:
We are not getting any callback handler when Image fails to load in ImageWithZoom component. 
**Why**:
This can be handy feature for handling wrong/Invalid  Url when image fails to load.
After that user can use alternate url
**How**:
Added OnLoad OnError props in ImageWithZoom component 
**Checklist**:
- [ N/A] Documentation added/updated

Add image loading error handling capabilities to ImageWithZoom #386

---

src/Slider/Slider.jsx

Hi, 
Bug brought up in #179, issue was identified by [third774](https://github.com/third774)
Fast drag and release would result in the carousel getting "stuck"
**What**:
Queued dragMove updates would occur after dragEnd resulting in the delta states not being zeroed within the Slider component
**Why**:
The changes fix the issue
**How**:
I removed the cancelAnimationFrame from handleOnTouchMove and added it to fakeOnDragMove which is used by both handleOnMouseMove and handleOnTouchMove and the method that requires the cancelling.
**Checklist**:
Thanks

Moved cancelAnimationFrame inside fakeOnDragMove

---

src/App/examples/Example14/Example14.jsx
src/Slider/Slider.jsx

**What**:
Fix bug on slider when dragging in `rtl` mode. If you drag to the left, the slider animates to the right (and vice-versa). This broken behaviour can be observed on the [examples page](https://express-labs.github.io/pure-react-carousel/#example--14).
See also [here](https://github.com/express-labs/pure-react-carousel/issues/97#issuecomment-738698238) and [here](https://github.com/express-labs/pure-react-carousel/issues/419).
**Why**:
Dragging on the carousel is broken for `rtl` pages.
**How**:
Rather than require a prop to be passed into the component, the `Slider` component detects whether the `direction` is `rtl` and inverts `deltaX` during drag accordingly.
**Checklist**:

Fix bug on slider when dragging in `rtl` mode
